on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0"

name: build
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      matrix:
        files:
          [
            {
              name: "system_0-499.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-",
            },
            {
              name: "system_500-999.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--500-999-",
            },
            {
              name: "system_1000-1299.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1000-1299-",
            },
            {
              name: "system_1300-1699.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-",
            },
            {
              name: "system_1700-3999.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1700-3999-",
            },
            {
              name: "system_4000-5999.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--4000-5999-",
            },
            {
              name: "system_6000-8199.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--6000-8199-",
            },
            {
              name: "system_8200-8999.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--8200-8999-",
            },
            {
              name: "system_9000-11999.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--9000-11999-",
            },
            {
              name: "system_12000-15999.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--12000-15999-",
            },
            {
              name: "wininet_12000-12999.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/wininet/wininet-errors",
            },
            {
              name: "winhttp_12000-12999.json",
              url: "https://docs.microsoft.com/en-us/windows/win32/winhttp/error-messages",
            },
          ]
    name: "Build ${{ matrix.files.name}}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Requirements
        run: |
          sudo apt update
          sudo apt -y install jq unzip wget curl
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          sudo unzip -d /usr/bin pup_v0.4.0_linux_amd64.zip
          rm pup_v0.4.0_linux_amd64.zip
      - name: build
        run: >
          curl ${{ matrix.files.url }} | 
              pup '.content > dl json{}' |
              jq '[.[0].children[].children[].children[]|select(.tag == "strong" or .children != null)]' |
              jq 'reduce .[] as $item ([];
                      if ($item.text) == null then
                          .[0:-1] + [.[-1] + [$item]]
                      else 
                          . + [[$item]]
                      end)' |
              jq '[.[]|select(.[1].children[1].text == null)]' |
              jq '[.[]|select(.[1].children[0].text|contains(" - ")|not)]' |
              jq 'map({
                  "title": .[0].text,
                  "code": .[1].children[0].text|split(" ")[0]|tonumber,
                  "msg": .[2:]|map(.children[].text)|join("\n\n")
              })' > ${{ matrix.files.name }}
      - name: commit
        uses: EndBug/add-and-commit@v7
        with:
          add: ${{ matrix.files.name }}
          default_author: github_actions
          message: Update ${{ matrix.files.name}}
  combine:
    needs: build
    runs-on: ubuntu-22.04
    name: "Combine results to all.json"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main # Get the latest result from build
      - name: Install Requirements
        run: |
          sudo apt update
          sudo apt -y install jq
      - name: Combine results
        run: |
          [ -e all.json ] && rm all.json
          jq -s . *.json | jq flatten > all.json
      - name: commit
        uses: EndBug/add-and-commit@v7
        with:
          add: all.json
          default_author: github_actions
          message: Update all.json
